#Create
POST http://localhost:3000/driver
Content-Type: application/json

{
  "name": "Juliana",
  "lastName": "Rocha",
  "driverLicense": "PRK314592",
  "document": "654.321.098-76",
  "phone": "(41) 93456-7890",
  "email": "ju.motorista@outlook.com",
  "password": "logistica10"
}

###

GET http://localhost:3000/driver
Content-Type: application/json

###
GET http://localhost:3000/driver/4507c107-af13-4141-8ac3-3fc4d12baab
Content-Type: application/json